name = "Sams Apocalypse Reworked"
author = "Sam"
version = "0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34ce388990e5f4a57fbb8cae8eb9039719b8034609f128dc0d2d9b2eccaa7986"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
