name = "Sams Apocalypse Reworked"
author = "Sam"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61d79504d9c19cc05af80244e95808b30bdd12bf9b158c0a984eeb8381ec2c2c"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
