name = "Sams Apocalypse Reworked"
author = "Sam"
version = "0.5.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f805b288b98fc5940a4a088c11b190ef4aafc65261cbda7d3bdce4d567bc78f"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
