name = "Sams Apocalypse Reworked"
author = "Sam"
version = "0.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8848bb7b4b9f7fb20a3d1cb65f1a6ca2323b14f309b0c9f86ade8dc93fe335ce"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
