name = "Sams Apocalypse Reworked"
author = "Sam"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c027e75b99a84c2c38f8383c4a88d2ee56f80af0b6d5979717d8112793931dde"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
