name = "Sams Apocalypse Reworked"
author = "Sam"
version = "0.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09cea41cf805ea2485db9705834a3c74e1eafe197d79ae295aa127b533b75311"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
