name = "Sams Apocalypse Reworked"
author = "Sam"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6737b91a6c2ec08a2aff9ddd4191eca5d1de7304d9bd316b3665d1363299c8fb"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
