name = "Sams Apocalypse Reworked"
author = "Sam"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c18f821d0321f4a367d8cf050bc5c9ca93de023d526dce555e5483b92659e760"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
