name = "Sams Apocalypse Reworked"
author = "Sam"
version = "0.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abcfd72bfcf89bc773ce6a6bc93a5e30bea9cc9ce97cef06fe71afd7e5ae2956"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
