name = "Sams Apocalypse Reworked"
author = "Sam"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "964a0cc831cebe42af55af525feca0522881aa6add30747a18053bbf4b5f0313"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
