name = "Sams Apocalypse Reworked"
author = "Sam"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4231b34835ef0b91bfe2f5eca7b24c29493efaf311296e70d377353c913ea39f"

[versions]
forge = "43.2.7"
minecraft = "1.19.2"
